[package]
name = "espress-wasm"
version = "0.1.0"
edition = "2021"
authors = ["espresso95"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Document",
  "Element",
  "HtmlElement",
  "Window",
]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false