[package]
name = "espress-os"
version = "0.1.0"
edition = "2021"
authors = ["espresso95"]
description = "A minimal bare-metal operating system kernel written in Rust for x86_64 architecture"
license = "MIT OR Apache-2.0"
repository = "https://github.com/espresso95/espress-os"
keywords = ["os", "kernel", "bare-metal", "x86_64", "vga"]
categories = ["embedded", "no-std", "os"]
readme = "../../../README.md"

[lib]
name = "espress_os"
path = "src/lib.rs"

[[bin]]
name = "espress-os"
path = "src/main.rs"
test = false
bench = false

[dependencies]
bootloader = "0.9.23"
volatile = "0.4.4"
spin = "0.9.4"
x86_64 = "0.14.2"
uart_16550 = "0.2.18"
pic8259 = "0.10.2"
pc-keyboard = "0.7.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio",
    "-display", "none"
]
test-success-exit-code = 33         # (0x10 << 1) | 1
test-timeout = 300                  # 5 minutes
