[build]
target = "i686-espress-os.json"

[target.i686-espress-os]
rustflags = ["-C", "link-arg=-T./linker.ld"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]